gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  filterMode: fuzzy
  showDivergenceFromBaseBranch: onlyArrow
  spinner:
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
    rate: 80
git:
  overrideGpg: true
  pagers:
    - pager: delta --dark --paging=never
